# =============================================
# School Lunch Express - application.properties
# MVP - Banco H2 em memória (DEV)
# =============================================

spring.application.name=lunch-express
server.port=8080

# ---- BANCO H2 (DEV/MVP) ----
#spring.datasource.url=jdbc:h2:mem:lunchexpress;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
#spring.datasource.driver-class-name=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=
#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Console H2 acessível em http://localhost:8080/h2-console
#spring.h2.console.enabled=true
#spring.h2.console.path=/h2-console


# ---- BANCO MYSQL (DOCKER / PRODUÇÃO) ----
spring.datasource.url=jdbc:mysql://localhost:3306/launchExpress?createDatabaseIfNotExist=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=123456
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect


# ---- JPA / HIBERNATE ----
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
# Mostra os valores dos parâmetros bindados nas queries
spring.jpa.properties.hibernate.use_sql_comments=true
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE

# ---- LOGGING GERAL ----
# Requests HTTP recebidos
logging.level.org.springframework.web=DEBUG
# Segurança / JWT
logging.level.org.springframework.security=INFO
# Nossa aplicação: tudo em DEBUG
logging.level.com.mackenzie.lunchexpress=DEBUG
# Transações
logging.level.org.springframework.transaction=DEBUG

# Formato do log no terminal
logging.pattern.console=%d{HH:mm:ss.SSS} %5p [%15.15t] %-40.40logger{39} : %m%n

# ---- JACKSON ----
spring.jackson.serialization.write-dates-as-timestamps=false
spring.jackson.deserialization.fail-on-unknown-properties=false

# ---- JWT ----
app.jwt.secret=SchoolLunchExpressMackenzieSuperSecretKeyADR022026!
app.jwt.expiration=86400000

# ---- CORS ----
app.cors.allowed-origins=*

# ---- PARA PRODUCAO (PostgreSQL) ----
# spring.datasource.url=jdbc:postgresql://localhost:5432/lunchexpress
# spring.datasource.username=postgres
# spring.datasource.password=suasenha
# spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
# spring.h2.console.enabled=false
